Repository NLog/NLog.Etw, pull requests merged in 2022-08, with the labels that each got.

#53 Package improvements, license and icon
  NLog.Etw/NLog.Etw.csproj
Labels: size/S

#55 Changed from Layout.Render to Target.RenderLogEvent
  NLog.Etw/EtwEventSourceTarget.cs
  NLog.Etw/NLogEtwExtendedTarget.cs
  NLog.Etw/NLogEtwTarget.cs
Labels: enhancement, size/S

#51 NLog 5 and version 5-rc1
  NLog.Etw/NLog.Etw.csproj
  appveyor.yml
  build.ps1
Labels: size/M
